---
deployment:
  tasks:
    # Copy files to deployment directory
    - export DEPLOYPATH=/home/maralatm/maralatmaca
    
    # Create necessary directories
    - mkdir -p $DEPLOYPATH
    
    # Copy application files (excluding node_modules and .next)
    - /bin/cp -R app $DEPLOYPATH/
    - /bin/cp -R components $DEPLOYPATH/
    - /bin/cp -R lib $DEPLOYPATH/
    - /bin/cp -R public $DEPLOYPATH/
    - /bin/cp -R scripts $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/
    - /bin/cp next.config.ts $DEPLOYPATH/
    - /bin/cp tsconfig.json $DEPLOYPATH/
    - /bin/cp tailwind.config.js $DEPLOYPATH/
    - /bin/cp postcss.config.mjs $DEPLOYPATH/
    - /bin/cp server.js $DEPLOYPATH/
    - /bin/cp .env.production $DEPLOYPATH/.env.production
    
    # Set permissions
    - chmod 755 $DEPLOYPATH
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    
    # Install dependencies and build (if Node.js is available)
    - cd $DEPLOYPATH && npm install --production && npm run build

